name: Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pr-preview-${{ github.event.number }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rossjrw/pr-preview-action@v1.8.1
        with:
          source-dir: ./
